
spring:
  application:
    name: user-service
  profiles:
#    active: dev
  datasource:
    url: mongodb://0.0.0.0:27017/earth
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  kafka:
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
      enable-auto-commit: true
